name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        hugo-version: latest # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: false # optional, default is false
