name: GoHugo
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: latest
        extended: false 

    - name: Hugo generate
      run: hugo

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: ./public
        ARGS: --parallel=5 --ignore-time
