name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: latest
        extended: false 

    - name: Hugo generate
      run: hugo

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USER }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#        # Protocol used to deploy (ftp or sftp)
#        #method: # optional, default is ftp
#        # The port used to connect to server
#        #port: # optional, default is 21
#        # The local folder to copy, defaults to root project folder
        LOCAL_DIR: ./public # optional, default is 
#        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        #remote_dir: # optional, default is 
        # Passes through options into lftp
        #ARGS: # optional, default is 
