name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

#    - name: Set up Go 1.13
#      uses: actions/setup-go@v1
#      with:
#        go-version: 1.13
#      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        # The Hugo version to download (if necessary) and use. Example: 0.58.2
        hugo-version: latest # optional, default is latest
        # Download (if necessary) and use Hugo extended version. Example: true
        extended: false # optional, default is false

    - name: Hugo generate
      run: hugo

    - name: List output files
      run: ls

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        # FTP server name (you may need to specify a port)
        ftp_server: w0067dbd.kasserver.com
        # FTP account username
        ftp_username: ${{ secrets.FTP_USER }}
        # FTP account password
        ftp_password: ${{ secrets.FTP_PASSWORD }}
#        # Protocol used to deploy (ftp or sftp)
#        #method: # optional, default is ftp
#        # The port used to connect to server
#        #port: # optional, default is 21
#        # The local folder to copy, defaults to root project folder
        local_dir: bildungsspender/public # optional, default is 
#        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        #remote_dir: # optional, default is 
        # Passes through options into lftp
        #ARGS: # optional, default is 
